### ISSUE TITLE
Add year to Special Log file name

### ISSUE THREAD

**Issue by bustacell** [Sp0ngeb0b/UrSGrappleExtension#1]
https://github.com/Sp0ngeb0b/UrSGrappleExtension/blob/8206fe8ba6f7cc87e4d02c27cbb4f4de03c4c365/Classes/URSGrappleClient.uc#L463

🙈

**Comment by bustacell** [comment]
General format should be `CTF-Combo_King-2020-03-06-23-32-13`
(Currently it is `CTF-Combo_King_6-3_23-36`)
Take leading zeros into account, if possible

TIA 👼

**Comment by Sp0ngeb0b** [comment]
I believe that the default demo manager format is `CTF-Combo_King_2-24_21-32-19` as I've never adjusted it to something else. `udemo.ini` included in 3.5 release package:

> Format=%L_%M-%D_%H-%O-%S

Still messed up day and month though. And adding the year to the demo manager makes sense anyways... :D

**Comment by Sp0ngeb0b** [comment]
Implemented in version 5l.
