### ISSUE TITLE
Add origin to Special Log entries

### ISSUE THREAD

**Issue by bustacell** [Sp0ngeb0b/UrSGrappleExtension#2]
https://github.com/Sp0ngeb0b/UrSGrappleExtension/blob/8206fe8ba6f7cc87e4d02c27cbb4f4de03c4c365/Classes/URSGrappleClient.uc#L484

Please add differentiator of log origins (automatically triggered via Insane Combo or manually triggered via binding) to log lines ☺️

**Comment by Sp0ngeb0b** [comment]
Implemented in version 5l.
